// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type AllSeatInfo struct {
	SeatInfos []SeatInfo `json:"seat_infos"`
}

type GetAllSeatInformationRequest struct {
	RoomIds []string `json:"room_ids"`
}

type GetRoomIdsResponse struct {
	RoomIds []string `json:"room_ids"`
}

type InLibraryRequest struct {
	Name    string   `json:"name"`
	RoomIds []string `json:"room_ids"`
}

type InLibraryResponse struct {
	IsInLibrary bool   `json:"is_in_library"`
	Area        string `json:"area"`
	Start       string `json:"start"`
	End         string `json:"end"`
}

type LoginRequest struct {
	UserName string `json:"username"`
	PassWord string `json:"password"`
}

type LoginResponse struct {
	Cookie []string `json:"cookie"`
}

type Response struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}

type SeatInfo struct {
	IsOccupied bool   `json:"is_occupied"`
	Owner      string `json:"owner"`
	Start      string `json:"start"`
	End        string `json:"end"`
}
