// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	"muxi-live-stream-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/library/inlibrary",
				Handler: InLibraryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/library/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/library/roomids",
				Handler: GetRoomIdsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/library/seatinfo",
				Handler: GetAllSeatInformationHandler(serverCtx),
			},
		},
	)
}
